"""add_history_timestamps

Revision ID: 650e01eb8c0b
Revises: bfdba6a42f0d
Create Date: 2026-06-08 19:59:37.801970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '650e01eb8c0b'
down_revision: Union[str, Sequence[str], None] = 'bfdba6a42f0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue_entries', sa.Column('served_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('queue_entries', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue_entries', 'resolved_at')
    op.drop_column('queue_entries', 'served_at')
    # ### end Alembic commands ###
